services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    ports:
      - "8000:8000" # Expose FastAPI on port 8000
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--workers",
        "4",
      ]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
