services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@message_store:5432/message_store
    depends_on:
      - message_store
    ports:
      - "8000:8000" # Expose FastAPI on port 8000
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--workers",
        "4",
      ]

  message_store:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_store
    ports:
      - "5432:5432"
    volumes:
      - message_store_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  message_store_data:
